name: tpAllPlayers
author: Theslowaja
main: Theslowaja\tpAllPlayers\TpAll
api: 4.0.0
version: 1.0.0

commands:
  tpall:
    description: Teleport All Player
    permission: tpall.command
    
permissions:
  tpall.command:
    default: op
